ARG IMAGE_NAME=container-registry.oracle.com/graalvm/jdk
ARG VERSION=17.0.8-ol9
# ARG VERSION=20.0.2-ol9

FROM ${IMAGE_NAME}:${VERSION} AS build

COPY /atomos_lib /build/atomos_lib
COPY /native-image-resources /build/native-image-resources


# Set up musl, in order to produce a static image compatible to alpine
# See 
# https://github.com/oracle/graal/issues/2824 and 
# https://github.com/oracle/graal/blob/vm-ce-22.0.0.2/docs/reference-manual/native-image/StaticImages.md
ARG RESULT_LIB="/musl"
RUN mkdir ${RESULT_LIB} && \
    curl -L -o musl.tar.gz https://more.musl.cc/10.2.1/x86_64-linux-musl/x86_64-linux-musl-native.tgz && \
    tar -xvzf musl.tar.gz -C ${RESULT_LIB} --strip-components 1 && \
    cp /usr/lib/gcc/x86_64-redhat-linux/11/libstdc++.a ${RESULT_LIB}/lib/
ENV CC=/musl/bin/gcc
RUN curl -L -o zlib.tar.gz https://zlib.net/zlib-1.2.13.tar.gz && \
    mkdir zlib && tar -xvzf zlib.tar.gz -C zlib --strip-components 1 && \
    cd zlib && ./configure --static --prefix=/musl && \
    make && make install && \
    cd / && rm -rf /zlib && rm -f /zlib.tar.gz
ENV PATH="$PATH:/musl/bin"


WORKDIR /build

RUN \
  gu install native-image && \
  dirlist=`find ./atomos_lib -type f -printf '%p:'` && \
  native-image \
#    -o atomos \
    --static \
    --libc=musl \
    --no-fallback \
    --initialize-at-build-time=org.apache.felix.atomos \
    --initialize-at-build-time=org.apache.felix.service.command.Converter \
    --class-path $dirlist \
    --verbose \
    -H:ConfigurationFileDirectories=native-image-resources \
    -H:+ReportUnsupportedElementsAtRuntime \
    -H:+ReportExceptionStackTraces \
    org.apache.felix.atomos.Atomos \
    atomos

CMD ["bash"]


FROM scratch

EXPOSE 11311

COPY --from=build /build/atomos /
COPY --from=build /build/atomos_lib /atomos_lib
COPY /etc /etc

CMD ["/atomos", "gosh.home=/", "gosh.args=--nointeractive -c telnetd -i 0.0.0.0 -p 11311 start"]
